### ISSUE TITLE
"resolve the IP address to each of the following fully qualified domain"

### ISSUE THREAD

**Issue by braultatgithub** [RHsyseng/5g-ran-deployments-on-ocp-lab#25]
In the Deployment chapter, https://labs.sysdeseng.com/5g-ran-deployments-on-ocp-lab/4.12/sno-intro.html#deployments, under the requirements for SNO section
It is mentioned that "You must configure the DNS to resolve the IP address to each of the **following** fully qualified domain names (FQDN)" Was there an intend to list those?

**Comment by alosadagrande** [comment]
Fixed. Thanks @braultatgithub
