### ISSUE TITLE
PTP overview

### ISSUE THREAD

**Issue by scollier** [RHsyseng/5g-ran-deployments-on-ocp-lab#3]
Should you link to these blog posts for more information about PTP?  

Part 1: 
https://cloud.redhat.com/blog/delivering-high-precision-clock-synchronization-for-low-latency-5g-networks-with-openshift-part-1

Part 2:
https://cloud.redhat.com/blog/delivering-high-accuracy-clock-synchronization-for-5g-networks-with-openshift-part-2

I'm referring to this section of the docs:

https://pages.sysdeseng.com/5g-ran-deployments-on-ocp-lab/5g-ran-deployments-on-ocp-lab/main/5g-ran-context.html#ptp

up to you.

**Comment by mvazquezc** [comment]
Added links [here](https://pages.sysdeseng.com/5g-ran-deployments-on-ocp-lab/5g-ran-deployments-on-ocp-lab/main/cnf-operators-intro.html#ptp-operator)
