### ISSUE TITLE
RHV no longer supported with OCP 4.14

### ISSUE THREAD

**Issue by dmoessne** [RHsyseng/5g-ran-deployments-on-ocp-lab#78]
According to 
-  https://github.com/RHsyseng/5g-ran-deployments-on-ocp-lab/blob/lab-4.14/documentation/modules/ROOT/pages/sno-intro.adoc#deployments

> OpenShift Container Platform on a Single Node is a specialized installation that requires the creation of a special ignition configuration ISO. It is supported on bare metal, vSphere, Red Hat OpenStack, **and Red Hat Virtualization** platforms as today

However, looking at 
- https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html#ocp-4-14-rhv-deprecations

> Red Hat Virtualization (RHV) as a host platform for OpenShift Container Platform was deprecated and is no longer supported.

So it is my understanding that we do no longer support RHV  with OCP 4.14  and the doc should reflect this

**Comment by mvazquezc** [comment]
Hey @dmoessne, 

Thank you for the heads up, I just updated the docs.
