### ISSUE TITLE
Ordinary Clock description specification

### ISSUE THREAD

**Issue by dmoessne** [RHsyseng/5g-ran-deployments-on-ocp-lab#80]
In 

- https://github.com/RHsyseng/5g-ran-deployments-on-ocp-lab/blob/lab-4.14/documentation/modules/ROOT/pages/5g-ran-context.adoc#ptp

`Ordinary Clock` is described as follows:

> Ordinary Clock: A PTP daemon connected to a GrandMaster to synchronize its clock.

However looking at the [following picture](https://labs.sysdeseng.com/5g-ran-deployments-on-ocp-lab/4.14/_images/ptp_diagram.png) it seems a `Ordinary Clock` can be connected either to a `GrandMaster` *or* a `Boundary Clock` . So I am wondering if the description of the `Ordinary Clock` should also mention the connection to `Boundary Clock` or if the pic is not accurate ?

**Comment by mvazquezc** [comment]
Well, I think it's a wording thing. 

For the ordinary clock, its GrandMaster can be a PTP Daemon acting as GrandMaster or a PTP Daemon acting as a boundary clock. What an ordinary clock will never be is GrandMaster for other PTP Daemons.

Does that help?

**Comment by alosadagrande** [comment]
Hey, I think the picture is accurate. The PTP Boundary clock behaves as an Ordinary clock (syncing with a Grandmaster clock) and as a Grandmaster for other Ordinary clocks. I agree, maybe we can improve the wording if it can be confusing right now.

**Comment by alosadagrande** [comment]
Notes added to the lab
